### ISSUE TITLE
About sync between devices with Newsboat

### ISSUE THREAD

**Issue by ghost** [NapoleonWils0n/ubuntu-dotfiles#2]
Sorry if this is not the place for this, but I need to know.
What I want to do is to open the feeds on an Android device instead of in the desktop as it is by default.

So, for example, to open the feeds in tabs inside firefox focus, instead of in the desktop's firefox browser.

Is this something that can be done?

The reason I am researching for this is because of eye strain. I have already found solutions to, for example, syncing articles from zotero  via zotfile and syncthing to my android e-book reader, but with newsboat I have not found anything equivalent. 

It is true that there is firefox sync, but I am searching for a way to synchronize locally as with zotero. 
If you are aware of anything let me know, please.

**Comment by NapoleonWils0n** [comment]
HI Mate

You can set the browser that opens links from newsboat but thats only for browsers on your local machine,
not for opening links on an android phone

Theres section in the newsboat documentation about using newsboat with newsreading services

[newsboat docs](https://newsboat.org/releases/2.27/docs/newsboat.html#_newsboat_as_a_client_for_newsreading_services)
