### ISSUE TITLE
Newsboat config?

### ISSUE THREAD

**Issue by UnclassedPenguin** [NapoleonWils0n/ubuntu-dotfiles#4]
Hey, not really an issue. Just wanted to ask, did you get rid of your Newsboat config? I found your video while looking into customizing Newsboat and clicked the link just to check out your config, and it 404'd. Went to the repository and don't see Newsboat config folder there anymore. Just curious. Your video already helped me solve my problem, so thanks!

**Comment by NapoleonWils0n** [comment]
hi mate, i switched to using elfeed with emacs

but you can still see my newsboat config here in my git history

https://github.com/NapoleonWils0n/ubuntu-dotfiles/tree/7457173cb4cfb37bb2d3808b7e5013f1ef02dd61/.config/newsboat

i just went back in time in my git history to when i made the video
no flux capacitor needed

ubuntu dot files history

https://github.com/NapoleonWils0n/ubuntu-dotfiles/commits/master/.config

im on Freebsd now and these are my latest dotfiles

https://github.com/NapoleonWils0n/freebsd-dotfiles-xps

all my tech notes

https://github.com/NapoleonWils0n/cerberus

ffmpeg scripts to do simple command line editing
including scene detection

https://github.com/NapoleonWils0n/ffmpeg-scripts

hope that helps

**Comment by UnclassedPenguin** [comment]
Hey, thanks for the quick reply. I've never heard of elfeed I'll have to check it out. Thanks for the link to your Newsboat config as well, I will check that out. Thanks again, you can close this "issue", ha.

**Comment by NapoleonWils0n** [comment]
Hi Mate, no problem

elfeed-tube video

https://www.youtube.com/watch?v=f6xWPiFvw4Y

heres my emacs config

https://github.com/NapoleonWils0n/freebsd-dotfiles-xps/tree/master/.config/emacs

i would reccomend these packages for elfeed

elfeed
https://github.com/skeeto/elfeed

elfeed-org
https://github.com/remyhonig/elfeed-org

elfeed-tube 
https://github.com/karthink/elfeed-tube

elfeed-tube-mpv

mpv
https://github.com/kljohann/mpv.el

my elfeed org file

https://github.com/NapoleonWils0n/feeds/blob/master/feeds.org
